/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerWorkspaceIdRouteImport } from './routes/explorer.$workspaceId'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ExplorerWorkspaceIdComponentComponentIdRouteImport } from './routes/explorer.$workspaceId.component.$componentId'
import { Route as ExplorerWorkspaceIdProjectProjectNameRouteImport } from './routes/explorer.$workspaceId.project.$projectName'
import { Route as ExplorerWorkspaceIdLibLibraryNameRouteImport } from './routes/explorer.$workspaceId.lib.$libraryName'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerWorkspaceIdRoute = ExplorerWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => ExplorerRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerWorkspaceIdComponentComponentIdRoute =
  ExplorerWorkspaceIdComponentComponentIdRouteImport.update({
    id: '/component/$componentId',
    path: '/component/$componentId',
    getParentRoute: () => ExplorerWorkspaceIdRoute,
  } as any)
const ExplorerWorkspaceIdProjectProjectNameRoute =
  ExplorerWorkspaceIdProjectProjectNameRouteImport.update({
    id: '/project/$projectName',
    path: '/project/$projectName',
    getParentRoute: () => ExplorerWorkspaceIdRoute,
  } as any)
const ExplorerWorkspaceIdLibLibraryNameRoute =
  ExplorerWorkspaceIdLibLibraryNameRouteImport.update({
    id: '/lib/$libraryName',
    path: '/lib/$libraryName',
    getParentRoute: () => ExplorerWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/explorer/$workspaceId': typeof ExplorerWorkspaceIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/explorer/$workspaceId/lib/$libraryName': typeof ExplorerWorkspaceIdLibLibraryNameRoute
  '/explorer/$workspaceId/project/$projectName': typeof ExplorerWorkspaceIdProjectProjectNameRoute
  '/explorer/$workspaceId/component/$componentId': typeof ExplorerWorkspaceIdComponentComponentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/explorer/$workspaceId': typeof ExplorerWorkspaceIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/explorer/$workspaceId/lib/$libraryName': typeof ExplorerWorkspaceIdLibLibraryNameRoute
  '/explorer/$workspaceId/project/$projectName': typeof ExplorerWorkspaceIdProjectProjectNameRoute
  '/explorer/$workspaceId/component/$componentId': typeof ExplorerWorkspaceIdComponentComponentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/explorer/$workspaceId': typeof ExplorerWorkspaceIdRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/explorer/$workspaceId/lib/$libraryName': typeof ExplorerWorkspaceIdLibLibraryNameRoute
  '/explorer/$workspaceId/project/$projectName': typeof ExplorerWorkspaceIdProjectProjectNameRoute
  '/explorer/$workspaceId/component/$componentId': typeof ExplorerWorkspaceIdComponentComponentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/login'
    | '/logout'
    | '/explorer/$workspaceId'
    | '/api/auth/callback'
    | '/explorer/$workspaceId/lib/$libraryName'
    | '/explorer/$workspaceId/project/$projectName'
    | '/explorer/$workspaceId/component/$componentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/login'
    | '/logout'
    | '/explorer/$workspaceId'
    | '/api/auth/callback'
    | '/explorer/$workspaceId/lib/$libraryName'
    | '/explorer/$workspaceId/project/$projectName'
    | '/explorer/$workspaceId/component/$componentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/login'
    | '/logout'
    | '/explorer/$workspaceId'
    | '/api/auth/callback'
    | '/explorer/$workspaceId/lib/$libraryName'
    | '/explorer/$workspaceId/project/$projectName'
    | '/explorer/$workspaceId/component/$componentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/$workspaceId': {
      id: '/explorer/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/explorer/$workspaceId'
      preLoaderRoute: typeof ExplorerWorkspaceIdRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/$workspaceId/component/$componentId': {
      id: '/explorer/$workspaceId/component/$componentId'
      path: '/component/$componentId'
      fullPath: '/explorer/$workspaceId/component/$componentId'
      preLoaderRoute: typeof ExplorerWorkspaceIdComponentComponentIdRouteImport
      parentRoute: typeof ExplorerWorkspaceIdRoute
    }
    '/explorer/$workspaceId/project/$projectName': {
      id: '/explorer/$workspaceId/project/$projectName'
      path: '/project/$projectName'
      fullPath: '/explorer/$workspaceId/project/$projectName'
      preLoaderRoute: typeof ExplorerWorkspaceIdProjectProjectNameRouteImport
      parentRoute: typeof ExplorerWorkspaceIdRoute
    }
    '/explorer/$workspaceId/lib/$libraryName': {
      id: '/explorer/$workspaceId/lib/$libraryName'
      path: '/lib/$libraryName'
      fullPath: '/explorer/$workspaceId/lib/$libraryName'
      preLoaderRoute: typeof ExplorerWorkspaceIdLibLibraryNameRouteImport
      parentRoute: typeof ExplorerWorkspaceIdRoute
    }
  }
}

interface ExplorerWorkspaceIdRouteChildren {
  ExplorerWorkspaceIdLibLibraryNameRoute: typeof ExplorerWorkspaceIdLibLibraryNameRoute
  ExplorerWorkspaceIdProjectProjectNameRoute: typeof ExplorerWorkspaceIdProjectProjectNameRoute
  ExplorerWorkspaceIdComponentComponentIdRoute: typeof ExplorerWorkspaceIdComponentComponentIdRoute
}

const ExplorerWorkspaceIdRouteChildren: ExplorerWorkspaceIdRouteChildren = {
  ExplorerWorkspaceIdLibLibraryNameRoute:
    ExplorerWorkspaceIdLibLibraryNameRoute,
  ExplorerWorkspaceIdProjectProjectNameRoute:
    ExplorerWorkspaceIdProjectProjectNameRoute,
  ExplorerWorkspaceIdComponentComponentIdRoute:
    ExplorerWorkspaceIdComponentComponentIdRoute,
}

const ExplorerWorkspaceIdRouteWithChildren =
  ExplorerWorkspaceIdRoute._addFileChildren(ExplorerWorkspaceIdRouteChildren)

interface ExplorerRouteChildren {
  ExplorerWorkspaceIdRoute: typeof ExplorerWorkspaceIdRouteWithChildren
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerWorkspaceIdRoute: ExplorerWorkspaceIdRouteWithChildren,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
