/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as DashboardV5RouteImport } from './routes/dashboard_.v5'
import { Route as DashboardV4RouteImport } from './routes/dashboard_.v4'
import { Route as DashboardV3RouteImport } from './routes/dashboard_.v3'
import { Route as DashboardV2RouteImport } from './routes/dashboard_.v2'
import { Route as DashboardV1RouteImport } from './routes/dashboard_.v1'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV5Route = DashboardV5RouteImport.update({
  id: '/dashboard_/v5',
  path: '/dashboard/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV4Route = DashboardV4RouteImport.update({
  id: '/dashboard_/v4',
  path: '/dashboard/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV3Route = DashboardV3RouteImport.update({
  id: '/dashboard_/v3',
  path: '/dashboard/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV2Route = DashboardV2RouteImport.update({
  id: '/dashboard_/v2',
  path: '/dashboard/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV1Route = DashboardV1RouteImport.update({
  id: '/dashboard_/v1',
  path: '/dashboard/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/dashboard/v1': typeof DashboardV1Route
  '/dashboard/v2': typeof DashboardV2Route
  '/dashboard/v3': typeof DashboardV3Route
  '/dashboard/v4': typeof DashboardV4Route
  '/dashboard/v5': typeof DashboardV5Route
  '/posts/$postId': typeof PostsPostIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/dashboard/v1': typeof DashboardV1Route
  '/dashboard/v2': typeof DashboardV2Route
  '/dashboard/v3': typeof DashboardV3Route
  '/dashboard/v4': typeof DashboardV4Route
  '/dashboard/v5': typeof DashboardV5Route
  '/posts/$postId': typeof PostsPostIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/dashboard_/v1': typeof DashboardV1Route
  '/dashboard_/v2': typeof DashboardV2Route
  '/dashboard_/v3': typeof DashboardV3Route
  '/dashboard_/v4': typeof DashboardV4Route
  '/dashboard_/v5': typeof DashboardV5Route
  '/posts/$postId': typeof PostsPostIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/teams'
    | '/dashboard/v1'
    | '/dashboard/v2'
    | '/dashboard/v3'
    | '/dashboard/v4'
    | '/dashboard/v5'
    | '/posts/$postId'
    | '/api/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/teams'
    | '/dashboard/v1'
    | '/dashboard/v2'
    | '/dashboard/v3'
    | '/dashboard/v4'
    | '/dashboard/v5'
    | '/posts/$postId'
    | '/api/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/teams'
    | '/dashboard_/v1'
    | '/dashboard_/v2'
    | '/dashboard_/v3'
    | '/dashboard_/v4'
    | '/dashboard_/v5'
    | '/posts/$postId'
    | '/api/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRoute
  DashboardV1Route: typeof DashboardV1Route
  DashboardV2Route: typeof DashboardV2Route
  DashboardV3Route: typeof DashboardV3Route
  DashboardV4Route: typeof DashboardV4Route
  DashboardV5Route: typeof DashboardV5Route
  PostsPostIdRoute: typeof PostsPostIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/v5': {
      id: '/dashboard_/v5'
      path: '/dashboard/v5'
      fullPath: '/dashboard/v5'
      preLoaderRoute: typeof DashboardV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/v4': {
      id: '/dashboard_/v4'
      path: '/dashboard/v4'
      fullPath: '/dashboard/v4'
      preLoaderRoute: typeof DashboardV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/v3': {
      id: '/dashboard_/v3'
      path: '/dashboard/v3'
      fullPath: '/dashboard/v3'
      preLoaderRoute: typeof DashboardV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/v2': {
      id: '/dashboard_/v2'
      path: '/dashboard/v2'
      fullPath: '/dashboard/v2'
      preLoaderRoute: typeof DashboardV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/v1': {
      id: '/dashboard_/v1'
      path: '/dashboard/v1'
      fullPath: '/dashboard/v1'
      preLoaderRoute: typeof DashboardV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRoute,
  DashboardV1Route: DashboardV1Route,
  DashboardV2Route: DashboardV2Route,
  DashboardV3Route: DashboardV3Route,
  DashboardV4Route: DashboardV4Route,
  DashboardV5Route: DashboardV5Route,
  PostsPostIdRoute: PostsPostIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
